// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudinary.OpenApiClient.Models;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Backup;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_asset_folder;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_asset_ids;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Image;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Raw;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Related_assets;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Restore;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Search;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Video;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Visual_search;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources
{
    /// <summary>
    /// Builds and executes requests for operations under \v1_1\{cloud_name}\resources
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResourcesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The backup property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Backup.BackupRequestBuilder Backup
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Backup.BackupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The by_asset_folder property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_asset_folder.By_asset_folderRequestBuilder By_asset_folder
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_asset_folder.By_asset_folderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The by_asset_ids property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_asset_ids.By_asset_idsRequestBuilder By_asset_ids
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_asset_ids.By_asset_idsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The by_external_ids property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder By_external_ids
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The image property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Image.ImageRequestBuilder Image
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Image.ImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The raw property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Raw.RawRequestBuilder Raw
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Raw.RawRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The related_assets property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Related_assets.Related_assetsRequestBuilder Related_assets
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Related_assets.Related_assetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restore property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Restore.RestoreRequestBuilder Restore
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Restore.RestoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The video property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Video.VideoRequestBuilder Video
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Video.VideoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The visual_search property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Visual_search.Visual_searchRequestBuilder Visual_search
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Visual_search.Visual_searchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Cloudinary.OpenApiClient.v1_1.item.resources.item collection</summary>
        /// <param name="position">The asset ID of the resource. Must be a 32-character hexadecimal string.</param>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder"/></returns>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("asset_%2Did", position);
                return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.ResourcesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResourcesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/resources", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.ResourcesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResourcesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/resources", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of all resource types that correspond to assets currently in your product environment.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Resource_types_response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.Models.Resource_types_response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.Models.Resource_types_response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cloudinary.OpenApiClient.Models.Resource_types_response>(requestInfo, global::Soenneker.Cloudinary.OpenApiClient.Models.Resource_types_response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of all resource types that correspond to assets currently in your product environment.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.ResourcesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.ResourcesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.ResourcesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
