// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudinary.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views
{
    /// <summary>
    /// Builds and executes requests for operations under \v1_1\{cloud_name}\video\analytics\views
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ViewsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ViewsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/video/analytics/views{?expression*,max_results*,next_cursor*,sort_by*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ViewsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/video/analytics/views{?expression*,max_results*,next_cursor*,sort_by*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves analytics data for video views. Results can be filtered using expressions based on various criteriasuch as video public ID, view duration, viewer information, and more.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsRequestBuilder.ViewsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsRequestBuilder.ViewsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsGetResponse>(requestInfo, global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves analytics data for video views. Results can be filtered using expressions based on various criteriasuch as video public ID, view duration, viewer information, and more.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsRequestBuilder.ViewsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsRequestBuilder.ViewsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.ViewsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves analytics data for video views. Results can be filtered using expressions based on various criteriasuch as video public ID, view duration, viewer information, and more.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ViewsRequestBuilderGetQueryParameters 
        {
            /// <summary>A set of conditions used to limit the results to rows that match those conditions. For example: `?expression=video_public_id=skate`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("expression")]
            public string? Expression { get; set; }
#nullable restore
#else
            [QueryParameter("expression")]
            public string Expression { get; set; }
#endif
            /// <summary>The maximum number of results to return. Default is 10.</summary>
            [QueryParameter("max_results")]
            public int? MaxResults { get; set; }
            /// <summary>The cursor for pagination. Use the next_cursor value from a previous response to get the next page of results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("next_cursor")]
            public string? NextCursor { get; set; }
#nullable restore
#else
            [QueryParameter("next_cursor")]
            public string NextCursor { get; set; }
#endif
            /// <summary>Specifies the expression field by which to sort the results. Prepend values with a &apos;-&apos; to reverse the order.</summary>
            [QueryParameter("sort_by")]
            public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.Analytics.Views.GetSort_byQueryParameterType? SortBy { get; set; }
        }
    }
}
#pragma warning restore CS0618
