// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>The type of access control to apply to the asset.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Access_control_item_access_type
    {
        [EnumMember(Value = "token")]
        #pragma warning disable CS1591
        Token,
        #pragma warning restore CS1591
        [EnumMember(Value = "anonymous")]
        #pragma warning disable CS1591
        Anonymous,
        #pragma warning restore CS1591
    }
}
