// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Binary_upload_request_responsive_breakpoints : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bytes_step property</summary>
        public int? BytesStep { get; set; }
        /// <summary>The create_derived property</summary>
        public bool? CreateDerived { get; set; }
        /// <summary>The max_images property</summary>
        public int? MaxImages { get; set; }
        /// <summary>The max_width property</summary>
        public int? MaxWidth { get; set; }
        /// <summary>The min_width property</summary>
        public int? MinWidth { get; set; }
        /// <summary>The transformation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Transformation { get; set; }
#nullable restore
#else
        public string Transformation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Binary_upload_request_responsive_breakpoints"/> and sets the default values.
        /// </summary>
        public Binary_upload_request_responsive_breakpoints()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Binary_upload_request_responsive_breakpoints"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.Binary_upload_request_responsive_breakpoints CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Binary_upload_request_responsive_breakpoints();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bytes_step", n => { BytesStep = n.GetIntValue(); } },
                { "create_derived", n => { CreateDerived = n.GetBoolValue(); } },
                { "max_images", n => { MaxImages = n.GetIntValue(); } },
                { "max_width", n => { MaxWidth = n.GetIntValue(); } },
                { "min_width", n => { MinWidth = n.GetIntValue(); } },
                { "transformation", n => { Transformation = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bytes_step", BytesStep);
            writer.WriteBoolValue("create_derived", CreateDerived);
            writer.WriteIntValue("max_images", MaxImages);
            writer.WriteIntValue("max_width", MaxWidth);
            writer.WriteIntValue("min_width", MinWidth);
            writer.WriteStringValue("transformation", Transformation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
