// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>The contextual-metadata operation to apply.- `add` merges the given key-value pairs into each asset&apos;s existing context. Keys  already present are overwritten; keys not mentioned are left intact. `context`  is required.- `remove_all` clears all contextual metadata. The `context` field is ignored.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ContextUpdateRequestCommand
    {
        [EnumMember(Value = "add")]
        #pragma warning disable CS1591
        Add,
        #pragma warning restore CS1591
        [EnumMember(Value = "remove_all")]
        #pragma warning disable CS1591
        RemoveAll,
        #pragma warning restore CS1591
    }
}
