// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>&quot;Output resolution tier, measured on the longest edge. Defaults to`1K` when omitted.* `0.5K`: ~512 px* `1K`: ~1024 px* `2K`: ~2048 px* `4K`: ~4096 px&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeclarativeImageSizeResolution
    {
        [EnumMember(Value = "0.5K")]
        #pragma warning disable CS1591
        Value05K,
        #pragma warning restore CS1591
        [EnumMember(Value = "1K")]
        #pragma warning disable CS1591
        Value1K,
        #pragma warning restore CS1591
        [EnumMember(Value = "2K")]
        #pragma warning disable CS1591
        Value2K,
        #pragma warning restore CS1591
        [EnumMember(Value = "4K")]
        #pragma warning disable CS1591
        Value4K,
        #pragma warning restore CS1591
    }
}
