// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// Declarative output size — an aspect ratio plus an optional resolutiontier, resolved server-side to the nearest size the model supports.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeclarativeImageSize : IParsable
    {
        /// <summary>Output aspect ratio, width-to-height. Limited to the core ratiosevery model supports natively.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.DeclarativeImageSizeAspectRatio? AspectRatio { get; set; }
        /// <summary>&quot;Output resolution tier, measured on the longest edge. Defaults to`1K` when omitted.* `0.5K`: ~512 px* `1K`: ~1024 px* `2K`: ~2048 px* `4K`: ~4096 px&quot;</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.DeclarativeImageSizeResolution? Resolution { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.DeclarativeImageSize"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.DeclarativeImageSize CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.DeclarativeImageSize();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aspect_ratio", n => { AspectRatio = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.DeclarativeImageSizeAspectRatio>(); } },
                { "resolution", n => { Resolution = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.DeclarativeImageSizeResolution>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.DeclarativeImageSizeAspectRatio>("aspect_ratio", AspectRatio);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.DeclarativeImageSizeResolution>("resolution", Resolution);
        }
    }
}
#pragma warning restore CS0618
