// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeliveryTypeAll_Wrapper_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "media_optimization")]
        #pragma warning disable CS1591
        Media_optimization,
        #pragma warning restore CS1591
    }
}
