// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// Details of an error, including a coarse category for retry logic, a stable error code, and a human-readable message.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Error : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;Coarse classification of an error, primarily used by clients to decide whether to retry.* `user_error`: the request was invalid; do not retry without changes.* `auth_error`: authentication or authorization failed.* `server_error`: an unexpected server-side error; retrying may succeed.* `rate_limit_error`: quota or rate limit exceeded; retry later.&quot;</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ErrorCategory? Category { get; set; }
        /// <summary>Stable, machine-readable error code for programmatic handling.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>Additional structured context about the error, when available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ErrorDetailsProperty? Details { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ErrorDetailsProperty Details { get; set; }
#endif
        /// <summary>Human-readable description of what went wrong.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Error"/> and sets the default values.
        /// </summary>
        public Error()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Error"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.Error CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Error();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "category", n => { Category = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.ErrorCategory>(); } },
                { "code", n => { Code = n.GetStringValue(); } },
                { "details", n => { Details = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.ErrorDetailsProperty>(global::Soenneker.Cloudinary.OpenApiClient.Models.ErrorDetailsProperty.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.ErrorCategory>("category", Category);
            writer.WriteStringValue("code", Code);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.ErrorDetailsProperty>("details", Details);
            writer.WriteStringValue("message", Message);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
