// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>The type of notification event.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventType
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "access_control_changed")]
        #pragma warning disable CS1591
        AccessControlChanged,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_refresh_auto_fetch")]
        #pragma warning disable CS1591
        BulkRefreshAutoFetch,
        #pragma warning restore CS1591
        [EnumMember(Value = "create_folder")]
        #pragma warning disable CS1591
        CreateFolder,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete_by_token")]
        #pragma warning disable CS1591
        DeleteByToken,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete_folder")]
        #pragma warning disable CS1591
        DeleteFolder,
        #pragma warning restore CS1591
        [EnumMember(Value = "eager")]
        #pragma warning disable CS1591
        Eager,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "explode")]
        #pragma warning disable CS1591
        Explode,
        #pragma warning restore CS1591
        [EnumMember(Value = "generate_archive")]
        #pragma warning disable CS1591
        GenerateArchive,
        #pragma warning restore CS1591
        [EnumMember(Value = "info")]
        #pragma warning disable CS1591
        Info,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalidate_custom_cdn")]
        #pragma warning disable CS1591
        InvalidateCustomCdn,
        #pragma warning restore CS1591
        [EnumMember(Value = "moderation")]
        #pragma warning disable CS1591
        Moderation,
        #pragma warning restore CS1591
        [EnumMember(Value = "moderation_summary")]
        #pragma warning disable CS1591
        ModerationSummary,
        #pragma warning restore CS1591
        [EnumMember(Value = "move")]
        #pragma warning disable CS1591
        Move,
        #pragma warning restore CS1591
        [EnumMember(Value = "move_or_rename_asset_folder")]
        #pragma warning disable CS1591
        MoveOrRenameAssetFolder,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi")]
        #pragma warning disable CS1591
        Multi,
        #pragma warning restore CS1591
        [EnumMember(Value = "publish")]
        #pragma warning disable CS1591
        Publish,
        #pragma warning restore CS1591
        [EnumMember(Value = "rename")]
        #pragma warning disable CS1591
        Rename,
        #pragma warning restore CS1591
        [EnumMember(Value = "report")]
        #pragma warning disable CS1591
        Report,
        #pragma warning restore CS1591
        [EnumMember(Value = "resource_context_changed")]
        #pragma warning disable CS1591
        ResourceContextChanged,
        #pragma warning restore CS1591
        [EnumMember(Value = "resource_display_name_changed")]
        #pragma warning disable CS1591
        ResourceDisplayNameChanged,
        #pragma warning restore CS1591
        [EnumMember(Value = "resource_metadata_changed")]
        #pragma warning disable CS1591
        ResourceMetadataChanged,
        #pragma warning restore CS1591
        [EnumMember(Value = "resource_tags_changed")]
        #pragma warning disable CS1591
        ResourceTagsChanged,
        #pragma warning restore CS1591
        [EnumMember(Value = "restore_asset_version")]
        #pragma warning disable CS1591
        RestoreAssetVersion,
        #pragma warning restore CS1591
        [EnumMember(Value = "sprite")]
        #pragma warning disable CS1591
        Sprite,
        #pragma warning restore CS1591
        [EnumMember(Value = "upload")]
        #pragma warning disable CS1591
        Upload,
        #pragma warning restore CS1591
    }
}
