// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.AssetDeliveryTypeWrapper3"/>, <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.FetchDeliveryTypeWrapper2"/>, <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.ManagedDeliveryTypeWrapper3"/>, <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.SocialDeliveryTypeWrapper2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExplicitDeliveryType : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.AssetDeliveryTypeWrapper3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.AssetDeliveryTypeWrapper3? AssetDeliveryTypeWrapper3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.AssetDeliveryTypeWrapper3 AssetDeliveryTypeWrapper3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.FetchDeliveryTypeWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.FetchDeliveryTypeWrapper2? FetchDeliveryTypeWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.FetchDeliveryTypeWrapper2 FetchDeliveryTypeWrapper2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.ManagedDeliveryTypeWrapper3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ManagedDeliveryTypeWrapper3? ManagedDeliveryTypeWrapper3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ManagedDeliveryTypeWrapper3 ManagedDeliveryTypeWrapper3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.SocialDeliveryTypeWrapper2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.SocialDeliveryTypeWrapper2? SocialDeliveryTypeWrapper2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.SocialDeliveryTypeWrapper2 SocialDeliveryTypeWrapper2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.ExplicitDeliveryType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.ExplicitDeliveryType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Cloudinary.OpenApiClient.Models.ExplicitDeliveryType();
            result.AssetDeliveryTypeWrapper3 = new global::Soenneker.Cloudinary.OpenApiClient.Models.AssetDeliveryTypeWrapper3();
            result.FetchDeliveryTypeWrapper2 = new global::Soenneker.Cloudinary.OpenApiClient.Models.FetchDeliveryTypeWrapper2();
            result.ManagedDeliveryTypeWrapper3 = new global::Soenneker.Cloudinary.OpenApiClient.Models.ManagedDeliveryTypeWrapper3();
            result.SocialDeliveryTypeWrapper2 = new global::Soenneker.Cloudinary.OpenApiClient.Models.SocialDeliveryTypeWrapper2();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AssetDeliveryTypeWrapper3 != null || FetchDeliveryTypeWrapper2 != null || ManagedDeliveryTypeWrapper3 != null || SocialDeliveryTypeWrapper2 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AssetDeliveryTypeWrapper3, FetchDeliveryTypeWrapper2, ManagedDeliveryTypeWrapper3, SocialDeliveryTypeWrapper2);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.AssetDeliveryTypeWrapper3>(null, AssetDeliveryTypeWrapper3, FetchDeliveryTypeWrapper2, ManagedDeliveryTypeWrapper3, SocialDeliveryTypeWrapper2);
        }
    }
}
#pragma warning restore CS0618
