// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>The status of the explode operation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Explode_response_status
    {
        [EnumMember(Value = "processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
    }
}
