// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Folder_roles_response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The roles the authenticated user can assign on this folder. Users can assign only roles at or below their own permission level for this folder. Returned only when `include_assignable_roles` is true.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Permitted_role>? PermittedRoles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Permitted_role> PermittedRoles { get; set; }
#endif
        /// <summary>An array of principals (users, groups, or API keys) with their role assignments on this folder, including roles inherited from ancestor folders.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Folder_role_assignment>? SharedWith { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Folder_role_assignment> SharedWith { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Folder_roles_response"/> and sets the default values.
        /// </summary>
        public Folder_roles_response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Folder_roles_response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.Folder_roles_response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Folder_roles_response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "permitted_roles", n => { PermittedRoles = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Permitted_role>(global::Soenneker.Cloudinary.OpenApiClient.Models.Permitted_role.CreateFromDiscriminatorValue)?.AsList(); } },
                { "shared_with", n => { SharedWith = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Folder_role_assignment>(global::Soenneker.Cloudinary.OpenApiClient.Models.Folder_role_assignment.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Permitted_role>("permitted_roles", PermittedRoles);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Folder_role_assignment>("shared_with", SharedWith);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
