// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// &quot;A generated asset: where it is stored (`storage`) plus its mediametadata. The media fields are populated once the task completes; anin-progress asset carries only `storage`.&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GeneratedAsset : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The size of the generated image in bytes.</summary>
        public long? Bytes { get; set; }
        /// <summary>The timestamp when the image was generated.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The image format of the stored asset.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.GeneratedAssetFormat? Format { get; set; }
        /// <summary>The height of the generated image in pixels; zero if the model doesn&apos;t provide dimensions.</summary>
        public int? Height { get; set; }
        /// <summary>Identifies the model that produced a generation result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ModelValue? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ModelValue Model { get; set; }
#endif
        /// <summary>The seed used for generation. Echoes input or returns the model-generated seed.Null when the model doesn&apos;t support seeds.</summary>
        public int? Seed { get; set; }
        /// <summary>Where a generated asset is stored — mirrors the request `target`,determined by `storage_type`. `secure_url` is always present.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Storage? Storage { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Storage Storage { get; set; }
#endif
        /// <summary>The width of the generated image in pixels; zero if the model doesn&apos;t provide dimensions.</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.GeneratedAsset"/> and sets the default values.
        /// </summary>
        public GeneratedAsset()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.GeneratedAsset"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.GeneratedAsset CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.GeneratedAsset();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bytes", n => { Bytes = n.GetLongValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "format", n => { Format = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.GeneratedAssetFormat>(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.ModelValue>(global::Soenneker.Cloudinary.OpenApiClient.Models.ModelValue.CreateFromDiscriminatorValue); } },
                { "seed", n => { Seed = n.GetIntValue(); } },
                { "storage", n => { Storage = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Storage>(global::Soenneker.Cloudinary.OpenApiClient.Models.Storage.CreateFromDiscriminatorValue); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("bytes", Bytes);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.GeneratedAssetFormat>("format", Format);
            writer.WriteIntValue("height", Height);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.ModelValue>("model", Model);
            writer.WriteIntValue("seed", Seed);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Storage>("storage", Storage);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
