// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// The archive generation parameters.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Generate_archive_request : global::Soenneker.Cloudinary.OpenApiClient.Models.Signature_parameters, IParsable
    {
        /// <summary>Whether to allow missing assets in the archive. If false, the operation will fail if any asset is not found.</summary>
        public bool? AllowMissing { get; set; }
        /// <summary>A list of asset folder paths to include in the archive, or a single folder path string. Only available when asset folders are enabled for your account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request.Generate_archive_request_asset_folders? AssetFolders { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request.Generate_archive_request_asset_folders AssetFolders { get; set; }
#endif
        /// <summary>(&quot;create&quot; mode only), specifies whether to generate the archive asynchronously.</summary>
        public bool? Async { get; set; }
        /// <summary>(&quot;download&quot; mode only) Unix timestamp indicating when the generated archive URL should expire.</summary>
        public long? ExpiresAt { get; set; }
        /// <summary>Whether to flatten all files to be in the root of the archive file.</summary>
        public bool? FlattenFolders { get; set; }
        /// <summary>Whether to flatten the folder structure of the derived assets.</summary>
        public bool? FlattenTransformations { get; set; }
        /// <summary>A list of fully qualified public IDs (resource_type/type/public_id) to include in the archive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FullyQualifiedPublicIds { get; set; }
#nullable restore
#else
        public List<string> FullyQualifiedPublicIds { get; set; }
#endif
        /// <summary>Whether to keep the derived assets used for generating the archive.</summary>
        public bool? KeepDerived { get; set; }
        /// <summary>The method for generating and delivering the archive. Options:download - Generates and delivers the archive file without storing itcreate - Creates and stores the archive as a raw asset, returning URLs in the responsecreate_and_download - Creates, stores, and delivers the archive file</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request_mode? Mode { get; set; }
        /// <summary>(&quot;create&quot; mode only), specifies the URL to notify when the archive generation is complete.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotificationUrl { get; set; }
#nullable restore
#else
        public string NotificationUrl { get; set; }
#endif
        /// <summary>Select all assets where the public ID starts with this prefix.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Prefixes { get; set; }
#nullable restore
#else
        public List<string> Prefixes { get; set; }
#endif
        /// <summary>The list of public IDs to include in the archive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PublicIds { get; set; }
#nullable restore
#else
        public List<string> PublicIds { get; set; }
#endif
        /// <summary>A search expression to select assets to include in the archive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchExpression { get; set; }
#nullable restore
#else
        public string SearchExpression { get; set; }
#endif
        /// <summary>Whether to skip adding the transformation details to the file names in the archive.</summary>
        public bool? SkipTransformationName { get; set; }
        /// <summary>Tags to filter which assets to include in the archive. Assets matching any of the specified tags are included.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The folder in your product environment where the generated archive should be stored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetAssetFolder { get; set; }
#nullable restore
#else
        public string TargetAssetFolder { get; set; }
#endif
        /// <summary>The filename for the downloaded archive file. Extension must match target_format (zip or tgz).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetFilename { get; set; }
#nullable restore
#else
        public string TargetFilename { get; set; }
#endif
        /// <summary>The format of the generated archive.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request_target_format? TargetFormat { get; set; }
        /// <summary>The public ID to assign to the generated archive, or the filename of the downloaded archive file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetPublicId { get; set; }
#nullable restore
#else
        public string TargetPublicId { get; set; }
#endif
        /// <summary>A list of tag names to assign to the generated archive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TargetTags { get; set; }
#nullable restore
#else
        public List<string> TargetTags { get; set; }
#endif
        /// <summary>The transformations to apply to the assets before including them in the archive (separated by &quot;|&quot;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Transformations { get; set; }
#nullable restore
#else
        public string Transformations { get; set; }
#endif
        /// <summary>All supported delivery types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all Type { get; set; }
#endif
        /// <summary>Whether to use the original filenames of the assets in the archive instead of public IDs (when available).</summary>
        public bool? UseOriginalFilename { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request"/> and sets the default values.
        /// </summary>
        public Generate_archive_request() : base()
        {
            Mode = global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request_mode.Create;
            TargetFormat = global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request_target_format.Zip;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "allow_missing", n => { AllowMissing = n.GetBoolValue(); } },
                { "asset_folders", n => { AssetFolders = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request.Generate_archive_request_asset_folders>(global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request.Generate_archive_request_asset_folders.CreateFromDiscriminatorValue); } },
                { "async", n => { Async = n.GetBoolValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetLongValue(); } },
                { "flatten_folders", n => { FlattenFolders = n.GetBoolValue(); } },
                { "flatten_transformations", n => { FlattenTransformations = n.GetBoolValue(); } },
                { "fully_qualified_public_ids", n => { FullyQualifiedPublicIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "keep_derived", n => { KeepDerived = n.GetBoolValue(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request_mode>(); } },
                { "notification_url", n => { NotificationUrl = n.GetStringValue(); } },
                { "prefixes", n => { Prefixes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "public_ids", n => { PublicIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "search_expression", n => { SearchExpression = n.GetStringValue(); } },
                { "skip_transformation_name", n => { SkipTransformationName = n.GetBoolValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "target_asset_folder", n => { TargetAssetFolder = n.GetStringValue(); } },
                { "target_filename", n => { TargetFilename = n.GetStringValue(); } },
                { "target_format", n => { TargetFormat = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request_target_format>(); } },
                { "target_public_id", n => { TargetPublicId = n.GetStringValue(); } },
                { "target_tags", n => { TargetTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "transformations", n => { Transformations = n.GetStringValue(); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all>(global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all.CreateFromDiscriminatorValue); } },
                { "use_original_filename", n => { UseOriginalFilename = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("allow_missing", AllowMissing);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request.Generate_archive_request_asset_folders>("asset_folders", AssetFolders);
            writer.WriteBoolValue("async", Async);
            writer.WriteLongValue("expires_at", ExpiresAt);
            writer.WriteBoolValue("flatten_folders", FlattenFolders);
            writer.WriteBoolValue("flatten_transformations", FlattenTransformations);
            writer.WriteCollectionOfPrimitiveValues<string>("fully_qualified_public_ids", FullyQualifiedPublicIds);
            writer.WriteBoolValue("keep_derived", KeepDerived);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request_mode>("mode", Mode);
            writer.WriteStringValue("notification_url", NotificationUrl);
            writer.WriteCollectionOfPrimitiveValues<string>("prefixes", Prefixes);
            writer.WriteCollectionOfPrimitiveValues<string>("public_ids", PublicIds);
            writer.WriteStringValue("search_expression", SearchExpression);
            writer.WriteBoolValue("skip_transformation_name", SkipTransformationName);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("target_asset_folder", TargetAssetFolder);
            writer.WriteStringValue("target_filename", TargetFilename);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request_target_format>("target_format", TargetFormat);
            writer.WriteStringValue("target_public_id", TargetPublicId);
            writer.WriteCollectionOfPrimitiveValues<string>("target_tags", TargetTags);
            writer.WriteStringValue("transformations", Transformations);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all>("type", Type);
            writer.WriteBoolValue("use_original_filename", UseOriginalFilename);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="string"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Generate_archive_request_asset_folders : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? GenerateArchiveRequestAssetFoldersString { get; set; }
#nullable restore
#else
            public string GenerateArchiveRequestAssetFoldersString { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request.Generate_archive_request_asset_folders"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request.Generate_archive_request_asset_folders CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Cloudinary.OpenApiClient.Models.Generate_archive_request.Generate_archive_request_asset_folders();
                if(parseNode.GetStringValue() is string generateArchiveRequestAssetFoldersStringValue)
                {
                    result.GenerateArchiveRequestAssetFoldersString = generateArchiveRequestAssetFoldersStringValue;
                }
                else if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GenerateArchiveRequestAssetFoldersString != null)
                {
                    writer.WriteStringValue(null, GenerateArchiveRequestAssetFoldersString);
                }
                else if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
