// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Info_last_updated : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access_control_updated_at property</summary>
        public DateTimeOffset? AccessControlUpdatedAt { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The context_updated_at property</summary>
        public DateTimeOffset? ContextUpdatedAt { get; set; }
        /// <summary>The metadata_updated_at property</summary>
        public DateTimeOffset? MetadataUpdatedAt { get; set; }
        /// <summary>The public_id_updated_at property</summary>
        public DateTimeOffset? PublicIdUpdatedAt { get; set; }
        /// <summary>The tags_updated_at property</summary>
        public DateTimeOffset? TagsUpdatedAt { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Info_last_updated"/> and sets the default values.
        /// </summary>
        public Info_last_updated()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Info_last_updated"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.Info_last_updated CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Info_last_updated();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_control_updated_at", n => { AccessControlUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "context_updated_at", n => { ContextUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "metadata_updated_at", n => { MetadataUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "public_id_updated_at", n => { PublicIdUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "tags_updated_at", n => { TagsUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("access_control_updated_at", AccessControlUpdatedAt);
            writer.WriteDateTimeOffsetValue("context_updated_at", ContextUpdatedAt);
            writer.WriteDateTimeOffsetValue("metadata_updated_at", MetadataUpdatedAt);
            writer.WriteDateTimeOffsetValue("public_id_updated_at", PublicIdUpdatedAt);
            writer.WriteDateTimeOffsetValue("tags_updated_at", TagsUpdatedAt);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
