// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Info : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access_control property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item>? AccessControl { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item> AccessControl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the asset is animated (e.g., GIF, animated WebP). Null for non-animated assets.</summary>
        public bool? Animated { get; set; }
        /// <summary>The aspect_ratio property</summary>
        public double? AspectRatio { get; set; }
        /// <summary>The asset_folder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssetFolder { get; set; }
#nullable restore
#else
        public string AssetFolder { get; set; }
#endif
        /// <summary>A 32-character hexadecimal asset ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssetId { get; set; }
#nullable restore
#else
        public string AssetId { get; set; }
#endif
        /// <summary>The backup property</summary>
        public bool? Backup { get; set; }
        /// <summary>The backup_bytes property</summary>
        public int? BackupBytes { get; set; }
        /// <summary>The bytes property</summary>
        public int? Bytes { get; set; }
        /// <summary>The colors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<UntypedNode>? Colors { get; set; }
#nullable restore
#else
        public List<UntypedNode> Colors { get; set; }
#endif
        /// <summary>Included if &apos;context=true&apos; parameter is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Context_full_response? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Context_full_response Context { get; set; }
#endif
        /// <summary>Face and custom coordinate data. Included if &apos;coordinates=true&apos; parameter is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Coordinates_response? Coordinates { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Coordinates_response Coordinates { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Included if &apos;derived=true&apos; parameter is used. Null when no derivatives exist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derivatives>? Derivatives { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derivatives> Derivatives { get; set; }
#endif
        /// <summary>The derived property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derived>? Derived { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derived> Derived { get; set; }
#endif
        /// <summary>The display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Duration in seconds for video/audio assets. Null for images.</summary>
        public double? Duration { get; set; }
        /// <summary>The etag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Etag { get; set; }
#nullable restore
#else
        public string Etag { get; set; }
#endif
        /// <summary>Detected face rectangles. Included if &apos;faces=true&apos; parameter is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Faces { get; set; }
#nullable restore
#else
        public UntypedNode Faces { get; set; }
#endif
        /// <summary>The filename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>The folder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Folder { get; set; }
#nullable restore
#else
        public string Folder { get; set; }
#endif
        /// <summary>The format property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Format { get; set; }
#nullable restore
#else
        public string Format { get; set; }
#endif
        /// <summary>The grayscale property</summary>
        public bool? Grayscale { get; set; }
        /// <summary>The height property</summary>
        public int? Height { get; set; }
        /// <summary>The illustration_score property</summary>
        public double? IllustrationScore { get; set; }
        /// <summary>Additional asset information (visual search, recognized people, etc.)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Info_info? InfoProp { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Info_info InfoProp { get; set; }
#endif
        /// <summary>The last_updated property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Info_last_updated? LastUpdated { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Info_last_updated LastUpdated { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Info_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Info_metadata Metadata { get; set; }
#endif
        /// <summary>Included if &apos;moderations=true&apos; parameter is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_moderation>? Moderation { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_moderation> Moderation { get; set; }
#endif
        /// <summary>The type of moderation applied to the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModerationKind { get; set; }
#nullable restore
#else
        public string ModerationKind { get; set; }
#endif
        /// <summary>The current status of the moderation process for the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModerationStatus { get; set; }
#nullable restore
#else
        public string ModerationStatus { get; set; }
#endif
        /// <summary>Cursor for paginating derived assets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextCursor { get; set; }
#nullable restore
#else
        public string NextCursor { get; set; }
#endif
        /// <summary>The pixels property</summary>
        public int? Pixels { get; set; }
        /// <summary>The predominant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Info_predominant? Predominant { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Info_predominant Predominant { get; set; }
#endif
        /// <summary>The public_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicId { get; set; }
#nullable restore
#else
        public string PublicId { get; set; }
#endif
        /// <summary>Related assets linked to this resource. Null when none linked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_related_assets>? RelatedAssets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_related_assets> RelatedAssets { get; set; }
#endif
        /// <summary>The subtype of the resource (e.g., for video). Null when not applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceSubtype { get; set; }
#nullable restore
#else
        public string ResourceSubtype { get; set; }
#endif
        /// <summary>The resource_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; set; }
#nullable restore
#else
        public string ResourceType { get; set; }
#endif
        /// <summary>The secure_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecureUrl { get; set; }
#nullable restore
#else
        public string SecureUrl { get; set; }
#endif
        /// <summary>The semi_transparent property</summary>
        public bool? SemiTransparent { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The substatus of the resource. Null when not set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Substatus { get; set; }
#nullable restore
#else
        public string Substatus { get; set; }
#endif
        /// <summary>Included if &apos;tags=true&apos; parameter is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>All supported delivery types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all Type { get; set; }
#endif
        /// <summary>The uploaded_at property</summary>
        public DateTimeOffset? UploadedAt { get; set; }
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The version property</summary>
        public int? Version { get; set; }
        /// <summary>The versions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_versions>? Versions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_versions> Versions { get; set; }
#endif
        /// <summary>The width property</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Info"/> and sets the default values.
        /// </summary>
        public Info()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Info"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.Info CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Info();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_control", n => { AccessControl = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item>(global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item.CreateFromDiscriminatorValue)?.AsList(); } },
                { "animated", n => { Animated = n.GetBoolValue(); } },
                { "aspect_ratio", n => { AspectRatio = n.GetDoubleValue(); } },
                { "asset_folder", n => { AssetFolder = n.GetStringValue(); } },
                { "asset_id", n => { AssetId = n.GetStringValue(); } },
                { "backup", n => { Backup = n.GetBoolValue(); } },
                { "backup_bytes", n => { BackupBytes = n.GetIntValue(); } },
                { "bytes", n => { Bytes = n.GetIntValue(); } },
                { "colors", n => { Colors = n.GetCollectionOfPrimitiveValues<UntypedNode>()?.AsList(); } },
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Context_full_response>(global::Soenneker.Cloudinary.OpenApiClient.Models.Context_full_response.CreateFromDiscriminatorValue); } },
                { "coordinates", n => { Coordinates = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Coordinates_response>(global::Soenneker.Cloudinary.OpenApiClient.Models.Coordinates_response.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "derivatives", n => { Derivatives = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derivatives>(global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derivatives.CreateFromDiscriminatorValue)?.AsList(); } },
                { "derived", n => { Derived = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derived>(global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derived.CreateFromDiscriminatorValue)?.AsList(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetDoubleValue(); } },
                { "etag", n => { Etag = n.GetStringValue(); } },
                { "faces", n => { Faces = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "folder", n => { Folder = n.GetStringValue(); } },
                { "format", n => { Format = n.GetStringValue(); } },
                { "grayscale", n => { Grayscale = n.GetBoolValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "illustration_score", n => { IllustrationScore = n.GetDoubleValue(); } },
                { "info", n => { InfoProp = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_info>(global::Soenneker.Cloudinary.OpenApiClient.Models.Info_info.CreateFromDiscriminatorValue); } },
                { "last_updated", n => { LastUpdated = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_last_updated>(global::Soenneker.Cloudinary.OpenApiClient.Models.Info_last_updated.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_metadata>(global::Soenneker.Cloudinary.OpenApiClient.Models.Info_metadata.CreateFromDiscriminatorValue); } },
                { "moderation", n => { Moderation = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_moderation>(global::Soenneker.Cloudinary.OpenApiClient.Models.Info_moderation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "moderation_kind", n => { ModerationKind = n.GetStringValue(); } },
                { "moderation_status", n => { ModerationStatus = n.GetStringValue(); } },
                { "next_cursor", n => { NextCursor = n.GetStringValue(); } },
                { "pixels", n => { Pixels = n.GetIntValue(); } },
                { "predominant", n => { Predominant = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_predominant>(global::Soenneker.Cloudinary.OpenApiClient.Models.Info_predominant.CreateFromDiscriminatorValue); } },
                { "public_id", n => { PublicId = n.GetStringValue(); } },
                { "related_assets", n => { RelatedAssets = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_related_assets>(global::Soenneker.Cloudinary.OpenApiClient.Models.Info_related_assets.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resource_subtype", n => { ResourceSubtype = n.GetStringValue(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "secure_url", n => { SecureUrl = n.GetStringValue(); } },
                { "semi_transparent", n => { SemiTransparent = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "substatus", n => { Substatus = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all>(global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all.CreateFromDiscriminatorValue); } },
                { "uploaded_at", n => { UploadedAt = n.GetDateTimeOffsetValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
                { "versions", n => { Versions = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_versions>(global::Soenneker.Cloudinary.OpenApiClient.Models.Info_versions.CreateFromDiscriminatorValue)?.AsList(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item>("access_control", AccessControl);
            writer.WriteBoolValue("animated", Animated);
            writer.WriteDoubleValue("aspect_ratio", AspectRatio);
            writer.WriteStringValue("asset_folder", AssetFolder);
            writer.WriteStringValue("asset_id", AssetId);
            writer.WriteBoolValue("backup", Backup);
            writer.WriteIntValue("backup_bytes", BackupBytes);
            writer.WriteIntValue("bytes", Bytes);
            writer.WriteCollectionOfPrimitiveValues<UntypedNode>("colors", Colors);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Context_full_response>("context", Context);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Coordinates_response>("coordinates", Coordinates);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derivatives>("derivatives", Derivatives);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_derived>("derived", Derived);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteDoubleValue("duration", Duration);
            writer.WriteStringValue("etag", Etag);
            writer.WriteObjectValue<UntypedNode>("faces", Faces);
            writer.WriteStringValue("filename", Filename);
            writer.WriteStringValue("folder", Folder);
            writer.WriteStringValue("format", Format);
            writer.WriteBoolValue("grayscale", Grayscale);
            writer.WriteIntValue("height", Height);
            writer.WriteDoubleValue("illustration_score", IllustrationScore);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_info>("info", InfoProp);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_last_updated>("last_updated", LastUpdated);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_metadata>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_moderation>("moderation", Moderation);
            writer.WriteStringValue("moderation_kind", ModerationKind);
            writer.WriteStringValue("moderation_status", ModerationStatus);
            writer.WriteStringValue("next_cursor", NextCursor);
            writer.WriteIntValue("pixels", Pixels);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_predominant>("predominant", Predominant);
            writer.WriteStringValue("public_id", PublicId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_related_assets>("related_assets", RelatedAssets);
            writer.WriteStringValue("resource_subtype", ResourceSubtype);
            writer.WriteStringValue("resource_type", ResourceType);
            writer.WriteStringValue("secure_url", SecureUrl);
            writer.WriteBoolValue("semi_transparent", SemiTransparent);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("substatus", Substatus);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Delivery_type_all>("type", Type);
            writer.WriteDateTimeOffsetValue("uploaded_at", UploadedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteIntValue("version", Version);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Info_versions>("versions", Versions);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
