// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>A reason code explaining why progress is unavailable. Present only when processed_assets_count is null.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InitialBackupProgressResponse_reason
    {
        [EnumMember(Value = "elasticsearch_not_enabled")]
        #pragma warning disable CS1591
        Elasticsearch_not_enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_results_from_search")]
        #pragma warning disable CS1591
        No_results_from_search,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_assets_were_processed")]
        #pragma warning disable CS1591
        No_assets_were_processed,
        #pragma warning restore CS1591
    }
}
