// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>Discriminator identifying this as managed-asset storage.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ManagedAssetStorageStorageType
    {
        [EnumMember(Value = "managed_asset")]
        #pragma warning disable CS1591
        ManagedAsset,
        #pragma warning restore CS1591
    }
}
