// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesOneOf2"/>, <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesWrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetadataRuleActivateValues : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesOneOf2? MetadataRuleActivateValuesOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesOneOf2 MetadataRuleActivateValuesOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesWrapper? MetadataRuleActivateValuesWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesWrapper MetadataRuleActivateValuesWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValues"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValues CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValues();
            if("MetadataRuleActivateValuesOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MetadataRuleActivateValuesOneOf2 = new global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesOneOf2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MetadataRuleActivateValuesOneOf2 != null)
            {
                return MetadataRuleActivateValuesOneOf2.GetFieldDeserializers();
            }
            else if(MetadataRuleActivateValuesWrapper != null)
            {
                return MetadataRuleActivateValuesWrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(MetadataRuleActivateValuesOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesOneOf2>(null, MetadataRuleActivateValuesOneOf2);
            }
            else if(MetadataRuleActivateValuesWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.MetadataRuleActivateValuesWrapper>(null, MetadataRuleActivateValuesWrapper);
            }
        }
    }
}
#pragma warning restore CS0618
