// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>Whether to override the current active set or append to it. Defaults to append.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MetadataRuleActivateValuesOneOf2Mode
    {
        [EnumMember(Value = "override")]
        #pragma warning disable CS1591
        OverrideValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "append")]
        #pragma warning disable CS1591
        Append,
        #pragma warning restore CS1591
    }
}
