// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>Exact model identifier; overrides family/tier when provided. The`-edit` models accept reference images and are selectable only on`image_to_image`; the others only on `text_to_image`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ModelByIdId
    {
        [EnumMember(Value = "nano-banana-1")]
        #pragma warning disable CS1591
        NanoBanana1,
        #pragma warning restore CS1591
        [EnumMember(Value = "nano-banana-2")]
        #pragma warning disable CS1591
        NanoBanana2,
        #pragma warning restore CS1591
        [EnumMember(Value = "flux-2-klein-9b")]
        #pragma warning disable CS1591
        Flux2Klein9B,
        #pragma warning restore CS1591
        [EnumMember(Value = "flux-2-pro")]
        #pragma warning disable CS1591
        Flux2Pro,
        #pragma warning restore CS1591
        [EnumMember(Value = "recraft-v3")]
        #pragma warning disable CS1591
        RecraftV3,
        #pragma warning restore CS1591
        [EnumMember(Value = "recraft-v4")]
        #pragma warning disable CS1591
        RecraftV4,
        #pragma warning restore CS1591
        [EnumMember(Value = "gpt-image-1-mini")]
        #pragma warning disable CS1591
        GptImage1Mini,
        #pragma warning restore CS1591
        [EnumMember(Value = "gpt-image-2")]
        #pragma warning disable CS1591
        GptImage2,
        #pragma warning restore CS1591
        [EnumMember(Value = "ideogram-v4-base")]
        #pragma warning disable CS1591
        IdeogramV4Base,
        #pragma warning restore CS1591
        [EnumMember(Value = "ideogram-v4-turbo")]
        #pragma warning disable CS1591
        IdeogramV4Turbo,
        #pragma warning restore CS1591
        [EnumMember(Value = "nano-banana-1-edit")]
        #pragma warning disable CS1591
        NanoBanana1Edit,
        #pragma warning restore CS1591
        [EnumMember(Value = "nano-banana-2-edit")]
        #pragma warning disable CS1591
        NanoBanana2Edit,
        #pragma warning restore CS1591
        [EnumMember(Value = "flux-2-klein-9b-edit")]
        #pragma warning disable CS1591
        Flux2Klein9BEdit,
        #pragma warning restore CS1591
        [EnumMember(Value = "flux-2-pro-edit")]
        #pragma warning disable CS1591
        Flux2ProEdit,
        #pragma warning restore CS1591
        [EnumMember(Value = "recraft-v3-edit")]
        #pragma warning disable CS1591
        RecraftV3Edit,
        #pragma warning restore CS1591
        [EnumMember(Value = "gpt-image-1-mini-edit")]
        #pragma warning disable CS1591
        GptImage1MiniEdit,
        #pragma warning restore CS1591
        [EnumMember(Value = "gpt-image-2-edit")]
        #pragma warning disable CS1591
        GptImage2Edit,
        #pragma warning restore CS1591
    }
}
