// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.ModelByFamily"/>, <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.ModelById"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ModelSelection : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.ModelByFamily"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ModelByFamily? ModelByFamily { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ModelByFamily ModelByFamily { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.ModelById"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ModelById? ModelById { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.ModelById ModelById { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.ModelSelection"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.ModelSelection CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Cloudinary.OpenApiClient.Models.ModelSelection();
            if("ModelByFamily".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ModelByFamily = new global::Soenneker.Cloudinary.OpenApiClient.Models.ModelByFamily();
            }
            else if("ModelById".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ModelById = new global::Soenneker.Cloudinary.OpenApiClient.Models.ModelById();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ModelByFamily != null)
            {
                return ModelByFamily.GetFieldDeserializers();
            }
            else if(ModelById != null)
            {
                return ModelById.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ModelByFamily != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.ModelByFamily>(null, ModelByFamily);
            }
            else if(ModelById != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.ModelById>(null, ModelById);
            }
        }
    }
}
#pragma warning restore CS0618
