// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// Status information returned for in-progress chunked uploads.Note that fields that are not yet determined or not known at the time of the call are omitted from the response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Non_final_chunk_upload_response : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The total number of bytes uploaded so far.</summary>
        public int? Bytes { get; set; }
        /// <summary>Whether the upload is complete. Will be false for all but the last chunk.</summary>
        public bool? Done { get; set; }
        /// <summary>The storage type of the asset. Defaults to &apos;upload&apos;.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Storage_type? Kind { get; set; }
        /// <summary>The public ID assigned to the upload. May be omitted in early chunks if it will be auto-generated upon completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicId { get; set; }
#nullable restore
#else
        public string PublicId { get; set; }
#endif
        /// <summary>The type of resource being uploaded (e.g., &quot;image&quot;, &quot;video&quot;, &quot;raw&quot;). May be omitted in early chunks when using auto detection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; set; }
#nullable restore
#else
        public string ResourceType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Non_final_chunk_upload_response"/> and sets the default values.
        /// </summary>
        public Non_final_chunk_upload_response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Non_final_chunk_upload_response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.Non_final_chunk_upload_response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Non_final_chunk_upload_response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bytes", n => { Bytes = n.GetIntValue(); } },
                { "done", n => { Done = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Storage_type>(); } },
                { "public_id", n => { PublicId = n.GetStringValue(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bytes", Bytes);
            writer.WriteBoolValue("done", Done);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Storage_type>("kind", Kind);
            writer.WriteStringValue("public_id", PublicId);
            writer.WriteStringValue("resource_type", ResourceType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
