// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// The rename request parameters.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Rename_request : global::Soenneker.Cloudinary.OpenApiClient.Models.Signature_parameters, IParsable
    {
        /// <summary>Whether to include contextual metadata in the response. Default is false.</summary>
        public bool? Context { get; set; }
        /// <summary>The public ID of the asset to rename.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromPublicId { get; set; }
#nullable restore
#else
        public string FromPublicId { get; set; }
#endif
        /// <summary>Whether to invalidate CDN cache copies of the renamed asset. Default is false.</summary>
        public bool? Invalidate { get; set; }
        /// <summary>Whether to include structured metadata in the response. Default is false.</summary>
        public bool? Metadata { get; set; }
        /// <summary>URL to notify when the operation is complete.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotificationUrl { get; set; }
#nullable restore
#else
        public string NotificationUrl { get; set; }
#endif
        /// <summary>Whether to overwrite the target asset if it already exists. Default is false.</summary>
        public bool? Overwrite { get; set; }
        /// <summary>The new public ID for the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToPublicId { get; set; }
#nullable restore
#else
        public string ToPublicId { get; set; }
#endif
        /// <summary>The target delivery type for the renamed asset. If omitted, the delivery type remains unchanged.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type? ToType { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type ToType { get; set; }
#endif
        /// <summary>The current delivery type of the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type Type { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Rename_request"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Cloudinary.OpenApiClient.Models.Rename_request CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Rename_request();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "context", n => { Context = n.GetBoolValue(); } },
                { "from_public_id", n => { FromPublicId = n.GetStringValue(); } },
                { "invalidate", n => { Invalidate = n.GetBoolValue(); } },
                { "metadata", n => { Metadata = n.GetBoolValue(); } },
                { "notification_url", n => { NotificationUrl = n.GetStringValue(); } },
                { "overwrite", n => { Overwrite = n.GetBoolValue(); } },
                { "to_public_id", n => { ToPublicId = n.GetStringValue(); } },
                { "to_type", n => { ToType = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type>(global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type>(global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("context", Context);
            writer.WriteStringValue("from_public_id", FromPublicId);
            writer.WriteBoolValue("invalidate", Invalidate);
            writer.WriteBoolValue("metadata", Metadata);
            writer.WriteStringValue("notification_url", NotificationUrl);
            writer.WriteBoolValue("overwrite", Overwrite);
            writer.WriteStringValue("to_public_id", ToPublicId);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type>("to_type", ToType);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_delivery_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
