// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Reorder_metadata_fields_request : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The direction to order by.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Direction_enum? Direction { get; set; }
        /// <summary>The field to order by.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Reorder_metadata_fields_request_order_by? OrderBy { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Reorder_metadata_fields_request"/> and sets the default values.
        /// </summary>
        public Reorder_metadata_fields_request()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Reorder_metadata_fields_request"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.Reorder_metadata_fields_request CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Reorder_metadata_fields_request();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "direction", n => { Direction = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Direction_enum>(); } },
                { "order_by", n => { OrderBy = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Reorder_metadata_fields_request_order_by>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Direction_enum>("direction", Direction);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Reorder_metadata_fields_request_order_by>("order_by", OrderBy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
