// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// Common parameters for resource search operations.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchParameters : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Fields or ranges to aggregate search results by. Requires a Tier 2 search plan; on Tier 1 the field is accepted but aggregations are omitted from the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.UnionBranch? Aggregate { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.UnionBranch Aggregate { get; set; }
#endif
        /// <summary>The Lucene-like search expression. Supports token match (`field:value`), exact match (`field=value`), trailing `*` for prefix match, ranges (`[a TO b]`, `{a TO b}`), and comparisons (`&gt;`, `&lt;`, `&gt;=`, `&lt;=`). Combine terms with uppercase `AND`, `OR`, `NOT`, or `+`/`-`, and group with parentheses. Wrap values containing reserved characters (spaces, colons, etc.) in double quotes. See the [search expressions guide](https://cloudinary.com/documentation/search_expressions.md) for the full syntax and supported fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Expression { get; set; }
#nullable restore
#else
        public string Expression { get; set; }
#endif
        /// <summary>&quot;A comma-separated list of fields to include in the response.Notes:- This parameter takes precedence over the with_field parameter, so if you want any additional asset attributes returned, make sure to also include them in this list (e.g., tags or context).- The following fields are always included in the response: public_id, asset_id, asset_folder, created_at, status, type, and resource_type.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fields { get; set; }
#nullable restore
#else
        public string Fields { get; set; }
#endif
        /// <summary>The maximum number of results to return. Default - 50. Maximum - 500.Set to `0` to get only `total_count` and `aggregations` without any resources in the response — useful for counting or aggregation-only queries.</summary>
        public int? MaxResults { get; set; }
        /// <summary>The cursor value to get the next page of results. Available when a previous search returned more results than max_results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextCursor { get; set; }
#nullable restore
#else
        public string NextCursor { get; set; }
#endif
        /// <summary>&quot;An array of single-key objects mapping a field to a sort direction. Each object must contain exactly one field name mapped to &apos;asc&apos; or &apos;desc&apos;.Default: [{\&quot;created_at\&quot;: \&quot;desc\&quot;}].&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters_sort_by>? SortBy { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters_sort_by> SortBy { get; set; }
#endif
        /// <summary>The additional asset attributes to include in each search result. The `fields` parameter takes precedence over this parameter. `image_metadata`, `image_analysis`, and `metadata` require a Tier 2 search plan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters_with_field?>? WithField { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters_with_field?> WithField { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters"/> and sets the default values.
        /// </summary>
        public SearchParameters()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aggregate", n => { Aggregate = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.UnionBranch>(global::Soenneker.Cloudinary.OpenApiClient.Models.UnionBranch.CreateFromDiscriminatorValue); } },
                { "expression", n => { Expression = n.GetStringValue(); } },
                { "fields", n => { Fields = n.GetStringValue(); } },
                { "max_results", n => { MaxResults = n.GetIntValue(); } },
                { "next_cursor", n => { NextCursor = n.GetStringValue(); } },
                { "sort_by", n => { SortBy = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters_sort_by>(global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters_sort_by.CreateFromDiscriminatorValue)?.AsList(); } },
                { "with_field", n => { WithField = n.GetCollectionOfEnumValues<global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters_with_field>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.UnionBranch>("aggregate", Aggregate);
            writer.WriteStringValue("expression", Expression);
            writer.WriteStringValue("fields", Fields);
            writer.WriteIntValue("max_results", MaxResults);
            writer.WriteStringValue("next_cursor", NextCursor);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters_sort_by>("sort_by", SortBy);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Cloudinary.OpenApiClient.Models.SearchParameters_with_field>("with_field", WithField);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
