// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>The access mode of the asset.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SearchResponseResourcesItemAccessMode
    {
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        PublicValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "authenticated")]
        #pragma warning disable CS1591
        Authenticated,
        #pragma warning restore CS1591
    }
}
