// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SearchParametersWithFieldItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "context")]
        #pragma warning disable CS1591
        Context,
        #pragma warning restore CS1591
        [EnumMember(Value = "tags")]
        #pragma warning disable CS1591
        Tags,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_metadata")]
        #pragma warning disable CS1591
        ImageMetadata,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_analysis")]
        #pragma warning disable CS1591
        ImageAnalysis,
        #pragma warning restore CS1591
        [EnumMember(Value = "metadata")]
        #pragma warning disable CS1591
        Metadata,
        #pragma warning restore CS1591
        [EnumMember(Value = "quality_analysis")]
        #pragma warning disable CS1591
        QualityAnalysis,
        #pragma warning restore CS1591
        [EnumMember(Value = "accessibility_analysis")]
        #pragma warning disable CS1591
        AccessibilityAnalysis,
        #pragma warning restore CS1591
    }
}
