// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>The active or inactive state.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StateEnum
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
    }
}
