// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>The tag operation to apply.- `add` adds the given tags, leaving existing tags untouched.- `remove` removes the given tags, leaving other tags untouched.- `replace` overwrites the full tag list with the given tags.- `remove_all` clears every tag. The `tags` field is ignored.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TagsUpdateRequestCommand
    {
        [EnumMember(Value = "add")]
        #pragma warning disable CS1591
        Add,
        #pragma warning restore CS1591
        [EnumMember(Value = "remove")]
        #pragma warning disable CS1591
        Remove,
        #pragma warning restore CS1591
        [EnumMember(Value = "replace")]
        #pragma warning disable CS1591
        Replace,
        #pragma warning restore CS1591
        [EnumMember(Value = "remove_all")]
        #pragma warning disable CS1591
        RemoveAll,
        #pragma warning restore CS1591
    }
}
