// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// An async generation task. Returned when a generation is accepted (202)and from GET /tasks/{task_id} as it progresses. The `result` is filledin once `status` is `completed`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaskObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Rate limit information for the account&apos;s add-on quotas.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Limits? Limits { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Limits Limits { get; set; }
#endif
        /// <summary>The generated assets. Populated once `status` is `completed`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.TaskResult? Result { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.TaskResult Result { get; set; }
#endif
        /// <summary>&quot;The status of an async generation task.* `pending`: accepted and queued, not yet started.* `processing`: generation is in progress.* `completed`: generation finished; `result` is populated.* `failed`: generation did not complete successfully.&quot;</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.TaskStatus? Status { get; set; }
        /// <summary>Identifier for the async generation task. Use it to poll `GET /generate/{cloud_name}/tasks/{task_id}`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskId { get; set; }
#nullable restore
#else
        public string TaskId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.TaskObject"/> and sets the default values.
        /// </summary>
        public TaskObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.TaskObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.TaskObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.TaskObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "limits", n => { Limits = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Limits>(global::Soenneker.Cloudinary.OpenApiClient.Models.Limits.CreateFromDiscriminatorValue); } },
                { "result", n => { Result = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.TaskResult>(global::Soenneker.Cloudinary.OpenApiClient.Models.TaskResult.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.TaskStatus>(); } },
                { "task_id", n => { TaskId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Limits>("limits", Limits);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.TaskResult>("result", Result);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.TaskStatus>("status", Status);
            writer.WriteStringValue("task_id", TaskId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
