// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Upload_response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The API key used to upload the file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKey { get; set; }
#nullable restore
#else
        public string ApiKey { get; set; }
#endif
        /// <summary>The asset ID of the uploaded file. This is the ID of the uploaded file in the Cloudinary database.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssetId { get; set; }
#nullable restore
#else
        public string AssetId { get; set; }
#endif
        /// <summary>The size of the uploaded file in bytes.</summary>
        public int? Bytes { get; set; }
        /// <summary>The date and time the file was uploaded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The eager property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_eager>? Eager { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_eager> Eager { get; set; }
#endif
        /// <summary>The ETag of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Etag { get; set; }
#nullable restore
#else
        public string Etag { get; set; }
#endif
        /// <summary>The format of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Format { get; set; }
#nullable restore
#else
        public string Format { get; set; }
#endif
        /// <summary>Whether the uploaded file is grayscale.</summary>
        public bool? Grayscale { get; set; }
        /// <summary>The height of the uploaded file.</summary>
        public int? Height { get; set; }
        /// <summary>The illustration score of the uploaded file.</summary>
        public double? IllustrationScore { get; set; }
        /// <summary>The image metadata of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_image_metadata? ImageMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_image_metadata ImageMetadata { get; set; }
#endif
        /// <summary>The original filename of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalFilename { get; set; }
#nullable restore
#else
        public string OriginalFilename { get; set; }
#endif
        /// <summary>The number of pages in the uploaded file.</summary>
        public int? Pages { get; set; }
        /// <summary>Whether the uploaded file is a placeholder.</summary>
        public bool? Placeholder { get; set; }
        /// <summary>The public ID of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicId { get; set; }
#nullable restore
#else
        public string PublicId { get; set; }
#endif
        /// <summary>The type of resource that was uploaded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; set; }
#nullable restore
#else
        public string ResourceType { get; set; }
#endif
        /// <summary>The secure URL of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecureUrl { get; set; }
#nullable restore
#else
        public string SecureUrl { get; set; }
#endif
        /// <summary>Whether the uploaded file is semi-transparent.</summary>
        public bool? SemiTransparent { get; set; }
        /// <summary>The signature of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Signature { get; set; }
#nullable restore
#else
        public string Signature { get; set; }
#endif
        /// <summary>The tags of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The type of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The URL of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The version of the uploaded file.</summary>
        public int? Version { get; set; }
        /// <summary>The version ID of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionId { get; set; }
#nullable restore
#else
        public string VersionId { get; set; }
#endif
        /// <summary>The width of the uploaded file.</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response"/> and sets the default values.
        /// </summary>
        public Upload_response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_key", n => { ApiKey = n.GetStringValue(); } },
                { "asset_id", n => { AssetId = n.GetStringValue(); } },
                { "bytes", n => { Bytes = n.GetIntValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "eager", n => { Eager = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_eager>(global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_eager.CreateFromDiscriminatorValue)?.AsList(); } },
                { "etag", n => { Etag = n.GetStringValue(); } },
                { "format", n => { Format = n.GetStringValue(); } },
                { "grayscale", n => { Grayscale = n.GetBoolValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "illustration_score", n => { IllustrationScore = n.GetDoubleValue(); } },
                { "image_metadata", n => { ImageMetadata = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_image_metadata>(global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_image_metadata.CreateFromDiscriminatorValue); } },
                { "original_filename", n => { OriginalFilename = n.GetStringValue(); } },
                { "pages", n => { Pages = n.GetIntValue(); } },
                { "placeholder", n => { Placeholder = n.GetBoolValue(); } },
                { "public_id", n => { PublicId = n.GetStringValue(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "secure_url", n => { SecureUrl = n.GetStringValue(); } },
                { "semi_transparent", n => { SemiTransparent = n.GetBoolValue(); } },
                { "signature", n => { Signature = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
                { "version_id", n => { VersionId = n.GetStringValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_key", ApiKey);
            writer.WriteStringValue("asset_id", AssetId);
            writer.WriteIntValue("bytes", Bytes);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_eager>("eager", Eager);
            writer.WriteStringValue("etag", Etag);
            writer.WriteStringValue("format", Format);
            writer.WriteBoolValue("grayscale", Grayscale);
            writer.WriteIntValue("height", Height);
            writer.WriteDoubleValue("illustration_score", IllustrationScore);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Upload_response_image_metadata>("image_metadata", ImageMetadata);
            writer.WriteStringValue("original_filename", OriginalFilename);
            writer.WriteIntValue("pages", Pages);
            writer.WriteBoolValue("placeholder", Placeholder);
            writer.WriteStringValue("public_id", PublicId);
            writer.WriteStringValue("resource_type", ResourceType);
            writer.WriteStringValue("secure_url", SecureUrl);
            writer.WriteBoolValue("semi_transparent", SemiTransparent);
            writer.WriteStringValue("signature", Signature);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("url", Url);
            writer.WriteIntValue("version", Version);
            writer.WriteStringValue("version_id", VersionId);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
