// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistBranch1"/>, <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistWrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UploadPresetInputAllOf2ParameterWhitelist : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistBranch1? UploadPresetInputAllOf2ParameterWhitelistBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistBranch1 UploadPresetInputAllOf2ParameterWhitelistBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistWrapper? UploadPresetInputAllOf2ParameterWhitelistWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistWrapper UploadPresetInputAllOf2ParameterWhitelistWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelist"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelist CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelist();
            if("UploadPresetInputAllOf2ParameterWhitelistBranch1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UploadPresetInputAllOf2ParameterWhitelistBranch1 = new global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistBranch1();
            }
            else if("UploadPresetInputAllOf2ParameterWhitelistWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UploadPresetInputAllOf2ParameterWhitelistWrapper = new global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistWrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(UploadPresetInputAllOf2ParameterWhitelistBranch1 != null)
            {
                return UploadPresetInputAllOf2ParameterWhitelistBranch1.GetFieldDeserializers();
            }
            else if(UploadPresetInputAllOf2ParameterWhitelistWrapper != null)
            {
                return UploadPresetInputAllOf2ParameterWhitelistWrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UploadPresetInputAllOf2ParameterWhitelistBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistBranch1>(null, UploadPresetInputAllOf2ParameterWhitelistBranch1);
            }
            else if(UploadPresetInputAllOf2ParameterWhitelistWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.Models.UploadPresetInputAllOf2ParameterWhitelistWrapper>(null, UploadPresetInputAllOf2ParameterWhitelistWrapper);
            }
        }
    }
}
#pragma warning restore CS0618
