// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.Models
{
    /// <summary>
    /// Upload size and pixel limits
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Usage_response_media_limits : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Maximum total pixels for assets</summary>
        public int? AssetMaxTotalPx { get; set; }
        /// <summary>Maximum pixels for images</summary>
        public int? ImageMaxPx { get; set; }
        /// <summary>Maximum size for images in bytes</summary>
        public int? ImageMaxSizeBytes { get; set; }
        /// <summary>Maximum size for raw files in bytes</summary>
        public int? RawMaxSizeBytes { get; set; }
        /// <summary>Maximum size for videos in bytes</summary>
        public int? VideoMaxSizeBytes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Usage_response_media_limits"/> and sets the default values.
        /// </summary>
        public Usage_response_media_limits()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Usage_response_media_limits"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.Models.Usage_response_media_limits CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.Models.Usage_response_media_limits();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "asset_max_total_px", n => { AssetMaxTotalPx = n.GetIntValue(); } },
                { "image_max_px", n => { ImageMaxPx = n.GetIntValue(); } },
                { "image_max_size_bytes", n => { ImageMaxSizeBytes = n.GetIntValue(); } },
                { "raw_max_size_bytes", n => { RawMaxSizeBytes = n.GetIntValue(); } },
                { "video_max_size_bytes", n => { VideoMaxSizeBytes = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("asset_max_total_px", AssetMaxTotalPx);
            writer.WriteIntValue("image_max_px", ImageMaxPx);
            writer.WriteIntValue("image_max_size_bytes", ImageMaxSizeBytes);
            writer.WriteIntValue("raw_max_size_bytes", RawMaxSizeBytes);
            writer.WriteIntValue("video_max_size_bytes", VideoMaxSizeBytes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
