// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Asset;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Derived_resources;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Download_backup;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Folder_operations;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Folders;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Metadata_fields;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Metadata_rules;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.People;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Streaming_profiles;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Tags;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Transformations;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Triggers;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Upload;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Upload_mappings;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Upload_presets;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Usage;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1_1\{cloud_name}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCloud_nameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The asset property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Asset.AssetRequestBuilder Asset
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Asset.AssetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The derived_resources property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Derived_resources.Derived_resourcesRequestBuilder Derived_resources
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Derived_resources.Derived_resourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download_backup property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Download_backup.Download_backupRequestBuilder Download_backup
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Download_backup.Download_backupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The folder_operations property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Folder_operations.Folder_operationsRequestBuilder Folder_operations
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Folder_operations.Folder_operationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The folders property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Folders.FoldersRequestBuilder Folders
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Folders.FoldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata_fields property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Metadata_fields.Metadata_fieldsRequestBuilder Metadata_fields
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Metadata_fields.Metadata_fieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata_rules property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Metadata_rules.Metadata_rulesRequestBuilder Metadata_rules
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Metadata_rules.Metadata_rulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The people property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.People.PeopleRequestBuilder People
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.People.PeopleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resources property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.ResourcesRequestBuilder Resources
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.ResourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The streaming_profiles property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Streaming_profiles.Streaming_profilesRequestBuilder Streaming_profiles
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Streaming_profiles.Streaming_profilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Tags.TagsRequestBuilder Tags
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transformations property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Transformations.TransformationsRequestBuilder Transformations
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Transformations.TransformationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The triggers property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Triggers.TriggersRequestBuilder Triggers
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Triggers.TriggersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Upload.UploadRequestBuilder Upload
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload_mappings property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Upload_mappings.Upload_mappingsRequestBuilder Upload_mappings
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Upload_mappings.Upload_mappingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload_presets property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Upload_presets.Upload_presetsRequestBuilder Upload_presets
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Upload_presets.Upload_presetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usage property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Usage.UsageRequestBuilder Usage
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Usage.UsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The video property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.VideoRequestBuilder Video
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Video.VideoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Cloudinary.OpenApiClient.v1_1.item.item collection</summary>
        /// <param name="position">The type of resource (image, video, raw, or auto).</param>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.WithResource_typeItemRequestBuilder"/></returns>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.WithResource_typeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("resource_type", position);
                return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.WithResource_typeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.WithCloud_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCloud_nameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.WithCloud_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCloud_nameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
