// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Cloudinary.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Rename
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RenamePostRequestBody : global::Soenneker.Cloudinary.OpenApiClient.Models.Signature_parameters, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Context metadata to update during rename.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Context { get; set; }
#nullable restore
#else
        public string Context { get; set; }
#endif
        /// <summary>The public ID of the asset to rename.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromPublicId { get; set; }
#nullable restore
#else
        public string FromPublicId { get; set; }
#endif
        /// <summary>Whether to invalidate the CDN cache for the renamed asset.</summary>
        public bool? Invalidate { get; set; }
        /// <summary>Structured metadata to update during rename.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>URL to notify when the operation is complete.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotificationUrl { get; set; }
#nullable restore
#else
        public string NotificationUrl { get; set; }
#endif
        /// <summary>Whether to overwrite the target asset if it already exists.</summary>
        public bool? Overwrite { get; set; }
        /// <summary>The new public ID for the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToPublicId { get; set; }
#nullable restore
#else
        public string ToPublicId { get; set; }
#endif
        /// <summary>The storage type of the resource.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Storage_type? ToType { get; set; }
        /// <summary>The storage type of the resource.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.Models.Storage_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Rename.RenamePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Rename.RenamePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Rename.RenamePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "context", n => { Context = n.GetStringValue(); } },
                { "from_public_id", n => { FromPublicId = n.GetStringValue(); } },
                { "invalidate", n => { Invalidate = n.GetBoolValue(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "notification_url", n => { NotificationUrl = n.GetStringValue(); } },
                { "overwrite", n => { Overwrite = n.GetBoolValue(); } },
                { "to_public_id", n => { ToPublicId = n.GetStringValue(); } },
                { "to_type", n => { ToType = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Storage_type>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Storage_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("context", Context);
            writer.WriteStringValue("from_public_id", FromPublicId);
            writer.WriteBoolValue("invalidate", Invalidate);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteStringValue("notification_url", NotificationUrl);
            writer.WriteBoolValue("overwrite", Overwrite);
            writer.WriteStringValue("to_public_id", ToPublicId);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Storage_type>("to_type", ToType);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.Models.Storage_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
