// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Destroy;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Download;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Explicit;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Explode;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Generate_archive;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Rename;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Upload;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Upload_chunked;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1_1\{cloud_name}\{resource_type}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithResource_typeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The destroy property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Destroy.DestroyRequestBuilder Destroy
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Destroy.DestroyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Download.DownloadRequestBuilder Download
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The explicit property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Explicit.ExplicitRequestBuilder Explicit
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Explicit.ExplicitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The explode property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Explode.ExplodeRequestBuilder Explode
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Explode.ExplodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The generate_archive property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Generate_archive.Generate_archiveRequestBuilder Generate_archive
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Generate_archive.Generate_archiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rename property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Rename.RenameRequestBuilder Rename
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Rename.RenameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The text property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextRequestBuilder Text
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Upload.UploadRequestBuilder Upload
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload_chunked property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Upload_chunked.Upload_chunkedRequestBuilder Upload_chunked
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Upload_chunked.Upload_chunkedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.WithResource_typeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResource_typeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/{resource_type}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.WithResource_typeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResource_typeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/{resource_type}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
