// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudinary.OpenApiClient.Models;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Context;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Item;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1_1\{cloud_name}\resources\{asset_-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Asset_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The context property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Context.ContextRequestBuilder Context
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Context.ContextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The moderations property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations.ModerationsRequestBuilder Moderations
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations.ModerationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Cloudinary.OpenApiClient.v1_1.item.resources.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Item.WithTypeItemRequestBuilder"/></returns>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Item.WithTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("type", position);
                return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Item.WithTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Asset_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/resources/{asset_%2Did}{?accessibility_analysis*,colors*,coordinates*,derived_next_cursor*,faces*,max_results*,media_metadata*,pages*,phash*,quality_analysis*,versions*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Asset_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/resources/{asset_%2Did}{?accessibility_analysis*,colors*,coordinates*,derived_next_cursor*,faces*,max_results*,media_metadata*,pages*,phash*,quality_analysis*,versions*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the details of a single resource specified by its asset ID.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Info"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.Models.Info?> GetAsync(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder.Asset_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.Models.Info> GetAsync(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder.Asset_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cloudinary.OpenApiClient.Models.Info>(requestInfo, global::Soenneker.Cloudinary.OpenApiClient.Models.Info.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates one or more attributes of a specified resource (asset) by its asset ID. This enables you to update details of an asset by its unique and immutable identifier, regardless of public ID, display name, asset folder, resource type or deliver type. Note that you can also update many attributes of an existing asset using the explicit method, which is not rate-limited.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Info"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.Models.Info?> PutAsync(global::Soenneker.Cloudinary.OpenApiClient.Models.ResourceUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.Models.Info> PutAsync(global::Soenneker.Cloudinary.OpenApiClient.Models.ResourceUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cloudinary.OpenApiClient.Models.Info>(requestInfo, global::Soenneker.Cloudinary.OpenApiClient.Models.Info.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the details of a single resource specified by its asset ID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder.Asset_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder.Asset_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates one or more attributes of a specified resource (asset) by its asset ID. This enables you to update details of an asset by its unique and immutable identifier, regardless of public ID, display name, asset folder, resource type or deliver type. Note that you can also update many attributes of an existing asset using the explicit method, which is not rate-limited.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Cloudinary.OpenApiClient.Models.ResourceUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Cloudinary.OpenApiClient.Models.ResourceUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Asset_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the details of a single resource specified by its asset ID.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Asset_ItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Whether to return accessibility analysis scores for the image. Default: false.</summary>
            [QueryParameter("accessibility_analysis")]
            public bool? AccessibilityAnalysis { get; set; }
            /// <summary>Whether to include color information (predominant colors and histogram of 32 leading colors). Default: false.</summary>
            [QueryParameter("colors")]
            public bool? Colors { get; set; }
            /// <summary>Whether to include previously specified custom cropping coordinates and faces coordinates. Default: false.</summary>
            [QueryParameter("coordinates")]
            public bool? Coordinates { get; set; }
            /// <summary>The cursor for the next page of derived assets when there are more derived images than max_results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("derived_next_cursor")]
            public string? DerivedNextCursor { get; set; }
#nullable restore
#else
            [QueryParameter("derived_next_cursor")]
            public string DerivedNextCursor { get; set; }
#endif
            /// <summary>Whether to include a list of coordinates of detected faces. Default: false.</summary>
            [QueryParameter("faces")]
            public bool? Faces { get; set; }
            /// <summary>Maximum number of derived assets to return. Default: 10.</summary>
            [QueryParameter("max_results")]
            public int? MaxResults { get; set; }
            /// <summary>Whether to include IPTC, XMP, and detailed Exif metadata in the response. Default: false.</summary>
            [QueryParameter("media_metadata")]
            public bool? MediaMetadata { get; set; }
            /// <summary>Whether to report the number of pages in multi-page documents (e.g., PDF). Default: false.</summary>
            [QueryParameter("pages")]
            public bool? Pages { get; set; }
            /// <summary>Whether to include the perceptual hash (pHash) of the uploaded photo for image similarity detection. Default: false.</summary>
            [QueryParameter("phash")]
            public bool? Phash { get; set; }
            /// <summary>Whether to return quality analysis scores for the image. Default: false.</summary>
            [QueryParameter("quality_analysis")]
            public bool? QualityAnalysis { get; set; }
            /// <summary>Whether to include details of all the backed up versions of the asset. Default: false.</summary>
            [QueryParameter("versions")]
            public bool? Versions { get; set; }
        }
    }
}
#pragma warning restore CS0618
