// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudinary.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids
{
    /// <summary>
    /// Builds and executes requests for operations under \v1_1\{cloud_name}\resources\by_external_ids
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class By_external_idsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public By_external_idsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/resources/by_external_ids?external_ids={external_ids}{&context*,fields*,metadata*,moderations*,resource_type*,tags*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public By_external_idsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/resources/by_external_ids?external_ids={external_ids}{&context*,fields*,metadata*,moderations*,resource_type*,tags*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves details for specific resources using their external IDs (or asset IDs).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.Models.ComponentsList_response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.Models.ComponentsList_response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder.By_external_idsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cloudinary.OpenApiClient.Models.ComponentsList_response> GetAsync(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder.By_external_idsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cloudinary.OpenApiClient.Models.Api_error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cloudinary.OpenApiClient.Models.ComponentsList_response>(requestInfo, global::Soenneker.Cloudinary.OpenApiClient.Models.ComponentsList_response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves details for specific resources using their external IDs (or asset IDs).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder.By_external_idsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder.By_external_idsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.By_external_idsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves details for specific resources using their external IDs (or asset IDs).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class By_external_idsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("context")]
            public bool? Context { get; set; }
            /// <summary>List of external IDs for identifying the assets to retrieve. Either external_ids or asset_ids must be provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("external_ids")]
            public string[]? ExternalIds { get; set; }
#nullable restore
#else
            [QueryParameter("external_ids")]
            public string[] ExternalIds { get; set; }
#endif
            /// <summary>A comma-separated list of fields to include in the response.Notes:This parameter takes precedence over other parameters requesting details in the response (e.g., tags or context), so include them in this list if you also want their details returned.The following fields are always included in the response: public_id, and asset_id.</summary>
            [QueryParameter("fields")]
            public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.By_external_ids.GetFieldsQueryParameterType? Fields { get; set; }
            [QueryParameter("metadata")]
            public bool? Metadata { get; set; }
            [QueryParameter("moderations")]
            public bool? Moderations { get; set; }
            /// <summary>Resource type (optional).</summary>
            [QueryParameter("resource_type")]
            public global::Soenneker.Cloudinary.OpenApiClient.Models.Resource_type? ResourceType { get; set; }
            [QueryParameter("tags")]
            public bool? Tags { get; set; }
        }
    }
}
#pragma warning restore CS0618
