// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Metadata_fields.Order
{
    /// <summary>The field to order by.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderPutRequestBody_order_by
    {
        [EnumMember(Value = "label")]
        #pragma warning disable CS1591
        Label,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "external_id")]
        #pragma warning disable CS1591
        External_id,
        #pragma warning restore CS1591
    }
}
