// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Cloudinary.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TextPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Restricts access to the asset by specifying one or more access types.The asset is restricted unless at least one listed access type is valid.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item>? AccessControl { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item> AccessControl { get; set; }
#endif
        /// <summary>The access mode of the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessMode { get; set; }
#nullable restore
#else
        public string AccessMode { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier of the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssetId { get; set; }
#nullable restore
#else
        public string AssetId { get; set; }
#endif
        /// <summary>Size of the asset in bytes.</summary>
        public int? Bytes { get; set; }
        /// <summary>The creation timestamp.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The display name of the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The ETag of the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Etag { get; set; }
#nullable restore
#else
        public string Etag { get; set; }
#endif
        /// <summary>The format of the generated image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Format { get; set; }
#nullable restore
#else
        public string Format { get; set; }
#endif
        /// <summary>The height of the generated image in pixels.</summary>
        public int? Height { get; set; }
        /// <summary>Additional information about the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_info? Info { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_info Info { get; set; }
#endif
        /// <summary>Moderation information for the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_moderation? Moderation { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_moderation Moderation { get; set; }
#endif
        /// <summary>Number of pages in the asset.</summary>
        public int? Pages { get; set; }
        /// <summary>Whether the asset is a placeholder.</summary>
        public bool? Placeholder { get; set; }
        /// <summary>The public identifier of the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicId { get; set; }
#nullable restore
#else
        public string PublicId { get; set; }
#endif
        /// <summary>Region information for the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_regions>? Regions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_regions> Regions { get; set; }
#endif
        /// <summary>The type of resource (image).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; set; }
#nullable restore
#else
        public string ResourceType { get; set; }
#endif
        /// <summary>The HTTPS URL for accessing the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecureUrl { get; set; }
#nullable restore
#else
        public string SecureUrl { get; set; }
#endif
        /// <summary>The signature for the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Signature { get; set; }
#nullable restore
#else
        public string Signature { get; set; }
#endif
        /// <summary>Array of tags assigned to the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The storage type of the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The HTTP URL for accessing the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The version number of the asset.</summary>
        public int? Version { get; set; }
        /// <summary>The version identifier of the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VersionId { get; set; }
#nullable restore
#else
        public string VersionId { get; set; }
#endif
        /// <summary>The width of the generated image in pixels.</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse"/> and sets the default values.
        /// </summary>
        public TextPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_control", n => { AccessControl = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item>(global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item.CreateFromDiscriminatorValue)?.AsList(); } },
                { "access_mode", n => { AccessMode = n.GetStringValue(); } },
                { "asset_id", n => { AssetId = n.GetStringValue(); } },
                { "bytes", n => { Bytes = n.GetIntValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "etag", n => { Etag = n.GetStringValue(); } },
                { "format", n => { Format = n.GetStringValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "info", n => { Info = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_info>(global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_info.CreateFromDiscriminatorValue); } },
                { "moderation", n => { Moderation = n.GetObjectValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_moderation>(global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_moderation.CreateFromDiscriminatorValue); } },
                { "pages", n => { Pages = n.GetIntValue(); } },
                { "placeholder", n => { Placeholder = n.GetBoolValue(); } },
                { "public_id", n => { PublicId = n.GetStringValue(); } },
                { "regions", n => { Regions = n.GetCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_regions>(global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_regions.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "secure_url", n => { SecureUrl = n.GetStringValue(); } },
                { "signature", n => { Signature = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
                { "version_id", n => { VersionId = n.GetStringValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.Models.Access_control_item>("access_control", AccessControl);
            writer.WriteStringValue("access_mode", AccessMode);
            writer.WriteStringValue("asset_id", AssetId);
            writer.WriteIntValue("bytes", Bytes);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteStringValue("etag", Etag);
            writer.WriteStringValue("format", Format);
            writer.WriteIntValue("height", Height);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_info>("info", Info);
            writer.WriteObjectValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_moderation>("moderation", Moderation);
            writer.WriteIntValue("pages", Pages);
            writer.WriteBoolValue("placeholder", Placeholder);
            writer.WriteStringValue("public_id", PublicId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostResponse_regions>("regions", Regions);
            writer.WriteStringValue("resource_type", ResourceType);
            writer.WriteStringValue("secure_url", SecureUrl);
            writer.WriteStringValue("signature", Signature);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("url", Url);
            writer.WriteIntValue("version", Version);
            writer.WriteStringValue("version_id", VersionId);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
