// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TextPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Name or RGB representation of the background color (e.g., red or</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Background { get; set; }
#nullable restore
#else
        public string Background { get; set; }
#endif
        /// <summary>Name or RGB representation of the font&apos;s color (e.g., red or</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FontColor { get; set; }
#nullable restore
#else
        public string FontColor { get; set; }
#endif
        /// <summary>The name of the font family.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FontFamily { get; set; }
#nullable restore
#else
        public string FontFamily { get; set; }
#endif
        /// <summary>Font size in points.</summary>
        public int? FontSize { get; set; }
        /// <summary>Whether to use a normal or italic font.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_font_style? FontStyle { get; set; }
        /// <summary>Whether to use a normal or bold font.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_font_weight? FontWeight { get; set; }
        /// <summary>The spacing between lines of text in pixels.</summary>
        public int? LineSpacing { get; set; }
        /// <summary>Text opacity value between 0 (invisible) and 100.</summary>
        public int? Opacity { get; set; }
        /// <summary>The identifier that is used for accessing the generated image. If not specified, a unique identifier is generated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicId { get; set; }
#nullable restore
#else
        public string PublicId { get; set; }
#endif
        /// <summary>The text string to generate an image for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>Text alignment (left, center, right, justify).</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_text_align? TextAlign { get; set; }
        /// <summary>Text decoration style.</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_text_decoration? TextDecoration { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody"/> and sets the default values.
        /// </summary>
        public TextPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            Background = "transparent";
            FontColor = "black";
            FontStyle = global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_font_style.Normal;
            FontWeight = global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_font_weight.Normal;
            TextDecoration = global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_text_decoration.None;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "background", n => { Background = n.GetStringValue(); } },
                { "font_color", n => { FontColor = n.GetStringValue(); } },
                { "font_family", n => { FontFamily = n.GetStringValue(); } },
                { "font_size", n => { FontSize = n.GetIntValue(); } },
                { "font_style", n => { FontStyle = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_font_style>(); } },
                { "font_weight", n => { FontWeight = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_font_weight>(); } },
                { "line_spacing", n => { LineSpacing = n.GetIntValue(); } },
                { "opacity", n => { Opacity = n.GetIntValue(); } },
                { "public_id", n => { PublicId = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "text_align", n => { TextAlign = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_text_align>(); } },
                { "text_decoration", n => { TextDecoration = n.GetEnumValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_text_decoration>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("background", Background);
            writer.WriteStringValue("font_color", FontColor);
            writer.WriteStringValue("font_family", FontFamily);
            writer.WriteIntValue("font_size", FontSize);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_font_style>("font_style", FontStyle);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_font_weight>("font_weight", FontWeight);
            writer.WriteIntValue("line_spacing", LineSpacing);
            writer.WriteIntValue("opacity", Opacity);
            writer.WriteStringValue("public_id", PublicId);
            writer.WriteStringValue("text", Text);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_text_align>("text_align", TextAlign);
            writer.WriteEnumValue<global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Item.Text.TextPostRequestBody_text_decoration>("text_decoration", TextDecoration);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
