// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.Image_to_image;
using Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.Tasks;
using Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.Text_to_image;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\generate\{cloudName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCloudNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The image_to_image property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.Image_to_image.Image_to_imageRequestBuilder Image_to_image
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.Image_to_image.Image_to_imageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The text_to_image property</summary>
        public global::Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.Text_to_image.Text_to_imageRequestBuilder Text_to_image
        {
            get => new global::Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.Text_to_image.Text_to_imageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.WithCloudNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCloudNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/generate/{cloudName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V2.Generate.Item.WithCloudNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCloudNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/generate/{cloudName}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
