// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1_1\{cloud_name}\resources\{asset_-id}\moderations\{moderation_kind}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithModeration_kindItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Cloudinary.OpenApiClient.v1_1.item.resources.item.moderations.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations.Item.Item.WithModeration_statusItemRequestBuilder"/></returns>
        public global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations.Item.Item.WithModeration_statusItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("moderation_status", position);
                return new global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations.Item.Item.WithModeration_statusItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations.Item.WithModeration_kindItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithModeration_kindItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/resources/{asset_%2Did}/moderations/{moderation_kind}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudinary.OpenApiClient.V1_1.Item.Resources.Item.Moderations.Item.WithModeration_kindItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithModeration_kindItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1_1/{cloud_name}/resources/{asset_%2Did}/moderations/{moderation_kind}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
